name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Check build output
        run: |
          if [ ! -f "dist/nodes/CountryStateCity/CountryStateCity.node.js" ]; then
            echo "Build failed: CountryStateCity.node.js not found"
            exit 1
          fi
          echo "Build successful: All required files generated"